query GetRainySeasons($userId: ID) {
  rainySeasons(
    sort: "id:desc", 
    pagination: { start: 0, limit: 50 },
    filters: { Usuario: { id: { eq: $userId } } }
  ) {
    data {
      id
      attributes {
        Slug
        Fecha
        Actividad
        Observaciones
        ProximaActividad
        NombreApiario
        NombreResponsable
        CodigoApiario
        CodigoUbicacion
        Ubicacion
      }
    }
  }
}
